### PR TITLE
Options widget improvements

### LINKED ISSUE #25: Show value of stretch on right of slider
It would be nice to show the value of the stretch (e.g. 0.5, 2, 3) on the right of the slider. This can be done with a QLabel that is updated when the slider is updated (I can do this if you like)

### PR DESCRIPTION
**Pull request by astrofrog**
@PennyQ @maxwelltsai - this tidied up the options widget a little and fixes https://github.com/glue-viz/glue-3d-viewer/issues/25

### CODE REVIEW

**Comment by PennyQ** [comment]
Thanks, this looks very great. I found that the py.test failed with `AttributeError: 'QtVispyWidget' object has no attribute 'axes'`, maybe you could just footnote the last line in 'test_vispy_widget.py' first (which causes this error) and merge it, later we could try to write a better structured test unit.

**Comment by astrofrog** [comment]
I just realized there is a change missing here, will commit later today (and that will fix error). I also want to make a few other improvements to the options widget, which I'll also make later today.

**Comment by astrofrog** [comment]
I accidentally opened this from a branch I pushed to this repo instead of my repository... I'll delete the branch from this repo once it's merged.

**Comment by astrofrog** [comment]
@PennyQ @maxwelltsai - I've done some significant refactoring to try and address both #25 and #35 as well as make sure things are better separated.

The options widget now includes a label giving the stretch value that auto-updates, and the ability to set that stretch value manually. In addition, the component of the data can now be selected, and the correct axis labels are used (instead of just RA/DEC/VEL).

The canvas-specific code setting e.g. camera and data parameters has been refactored and is now in the vispy widget rather than in the options widget. The options widget is kept as simple as possible and simply triggers a refresh from the data viewer when any options are updated. Before, the options widget had to go and modify the camera elements, which is not ideal.

The diff is going to be hard to read, but I encourage you to look at the code in the branch:

https://github.com/glue-viz/glue-3d-viewer/tree/options-improvements/vispy_volume

And also feel free to try out that branch to check if anything is broken (if you prefer, we can merge and then you can test it out, I'll leave that up to you).

**Comment by astrofrog** [comment]
Screenshot of current options widget:

screen shot 2015-10-02 at 5 02 01 pm

**Comment by PennyQ** [comment]
@astrofrog This looks so great, very looking forward to seeing it be merged.
Maxwell and I have been worked on the #30 for sometime but it still has some problems. The test Python file is listed here https://github.com/PennyQ/Test/blob/master/volume_test_axis.py and any advice would be very helpful.

**Comment by astrofrog** [comment]
@PennyQ - Thanks for reviewing! Will merge now - I hope this doesn't cause to many conflicts for your changes relating to the axes!

**Pull request merged**
