### PR TITLE
Side panel

### PR DESCRIPTION
**Pull request by PennyQ**
Text optimization & Viewer scale set

### CODE REVIEW

**Comment by PennyQ** [comment]
Sorry that I tried to merge branch `PennyQ:side_panel` to the `PennyQ:master` in my fork repository but made a mistake to merge it into the `glue-viz:master` and closed this pull-request :(

I optimized the text status display under the suggestion of @maxwelltsai with a `Timer` and also put it into a proper location. The scale of `Viewer` in Glue is set as same as that of  `canvas` in VisPy now and I will try to modify the scale of the huge `Volume` later.

**Comment by astrofrog** [comment]
@PennyQ - no problem about the mistake :) You can avoid this in future by changing the upstream remote to be read-only by using http:

```
$ git remote rm upstream
$ git remote add upstream http://github.com/glue-viz/glue-3d-viewer.git
```

Try doing this and then check the output of:

```
$ git remote -v
```

which should look like:

```
origin  git@github.com:PennyQ/glue-3d-viewer.git (fetch)
origin  git@github.com:PennyQ/glue-3d-viewer.git (push)
upstream    http://github.com/glue-viz/glue-3d-viewer.git (fetch)
upstream    http://github.com/glue-viz/glue-3d-viewer.git (push)
```

Does it look like this?

It takes a little while to get used to git :)

**Comment by PennyQ** [comment]
@astrofrog Thank you so much. Actually my remote lists are like this:

```
origin  https://github.com/PennyQ/glue-3d-viewer.git (fetch)
origin  https://github.com/PennyQ/glue-3d-viewer.git (push)
upstream    http://github.com/glue-viz/glue-3d-viewer.git (fetch)
upstream    http://github.com/glue-viz/glue-3d-viewer.git (push)
```

Is `git@github.com:PennyQ` the same as `https://github.com/PennyQ`, why could such a difference appear?
Does it mean that If I change it from `https` to `http` , then the `push` command cannot work and I can only `fetch` remote code from that remote URL?

**Comment by astrofrog** [comment]
@PennyQ - yes, you can't push to a plain http remote.

Just to make sure I understand, did you accidentally push to master or was it that you clicked 'Merge pull request' but you thought the pull request was to PennyQ?

If you like I can make your access to glue-3d-viewer read-only for now if you want to be safe from accidentally pushing to the main repository?

**Comment by PennyQ** [comment]
Hi Tom, I clicked the 'Merge Pull Request' and then found I mistakenly merged to the master repository, I don't think I'll make that mistake again and I'm getting familiar with GitHub :)
Thank you for your help and you are so kind. Looking forward to reaching the milestone of this project.

**Pull request merged**
