### PR TITLE
add back the fov=60

### PR DESCRIPTION
**Pull request by PennyQ**
Solve the #102 for scatter plot viewer

@astrofrog Could we merge the https://github.com/glue-viz/glue-3d-viewer/pull/103 and I could add this to volume viewer too :)

### CODE REVIEW

**Comment by astrofrog** [comment]
#103 is merged :) However it looks like you'll have to rebase this as a result :-/

**Comment by PennyQ** [comment]
@astrofrog Here we go :)

**Comment by astrofrog** [comment]
@PennyQ - thanks! It looks like there might be code missing for the scatter plot selection?

**Comment by PennyQ** [comment]
@astrofrog I added that in the #103 PR and it's merged already, now I think I should put it here to make each PR doing the same thing, I'll try to be careful about it in my future work :)

**Comment by astrofrog** [comment]
Thanks @PennyQ!

**Pull request merged**
