### PR TITLE
Issue with cubes > 2048 in one dimension in volume rendering

### PR DESCRIPTION
**Pull request by astrofrog**
cc @stscieisenhamer

### CODE REVIEW

**Comment by astrofrog** [comment]
We need to make a minimal example and report to VisPy

**Comment by stscieisenhamer** [comment]
Two files are in the zip, one dimensioned (2048, 5, 5), the other (2049, 5, 5). Upon rendering the 2048 length one works, and only reports the following:

```
2016-03-31 16:50:12.928 python[6169:204740] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
WARNING: OpenGL version 3.0 or higher recommended, got 2.1 NVIDIA-10.4.2 310.41.35f01. Some functionality may fail.
WARNING:vispy:OpenGL version 3.0 or higher recommended, got 2.1 NVIDIA-10.4.2 310.41.35f01. Some functionality may fail.
Validation Failed: Current draw framebuffer is invalid.
```

The 2049 one does not render and reports:

```
2016-03-31 16:47:09.850 python[6169:204740] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
WARNING: OpenGL version 3.0 or higher recommended, got 2.1 NVIDIA-10.4.2 310.41.35f01. Some functionality may fail.
WARNING:vispy:OpenGL version 3.0 or higher recommended, got 2.1 NVIDIA-10.4.2 310.41.35f01. Some functionality may fail.
INFO: Program has unset variables: {'u_scale_4', 'u_shape', 'u_inv_matrix_1', 'u_scale_6', 'u_matrix_1', 'u_scale_5', 'u_weight_9', 'u_volumetex_0', 'u_enabled_8', 'u_matrix', 'u_weight_4', 'u_weight_6', 'u_translate_7', 'u_volumetex_1', 'u_volumetex_3', 'u_weight_2', 'u_weight_8', 'u_volumetex_6', 'u_translate', 'u_translate_1', 'u_translate_4', 'u_enabled_4', 'u_scale_7', 'u_view', 'u_translate_2', 'u_translate_6', 'u_weight_0', 'u_volumetex_7', 'u_scale_1', 'u_enabled_9', 'u_translate_3', 'u_volumetex_9', 'u_scale_2', 'u_translate_5', 'u_weight_7', 'u_volumetex_5', 'u_inv_matrix', 'u_scale_3', 'u_scale', 'u_volumetex_8'}
INFO:vispy:Program has unset variables: {'u_scale_4', 'u_shape', 'u_inv_matrix_1', 'u_scale_6', 'u_matrix_1', 'u_scale_5', 'u_weight_9', 'u_volumetex_0', 'u_enabled_8', 'u_matrix', 'u_weight_4', 'u_weight_6', 'u_translate_7', 'u_volumetex_1', 'u_volumetex_3', 'u_weight_2', 'u_weight_8', 'u_volumetex_6', 'u_translate', 'u_translate_1', 'u_translate_4', 'u_enabled_4', 'u_scale_7', 'u_view', 'u_translate_2', 'u_translate_6', 'u_weight_0', 'u_volumetex_7', 'u_scale_1', 'u_enabled_9', 'u_translate_3', 'u_volumetex_9', 'u_scale_2', 'u_translate_5', 'u_weight_7', 'u_volumetex_5', 'u_inv_matrix', 'u_scale_3', 'u_scale', 'u_volumetex_8'}
```

[random.zip](https://github.com/glue-viz/glue-3d-viewer/files/198576/random.zip)

**Comment by astrofrog** [comment]
Thanks! I've opened an issue on the Vispy tracker: https://github.com/vispy/vispy/issues/1197

**Comment by astrofrog** [comment]
Workaround attached for now - this causes the array to be block-reduced on-the-fly. I think we should be block_reducing with mean (and I think default is sum) so that needs fixing. Also, it might be nice to have the option to control the block size for block reduce since this could be generically useful.

**Comment by astrofrog** [comment]
@stscieisenhamer - so this turns out to be an OpenGL limitation (at least a limitation of the graphics cards we have) so for now, if the array is > 2048 is any one dimension, I rebin it on-the-fly as needed.

Could you check whether you are now able to load the full data file you were trying before?

**Pull request merged**
