### PR TITLE
Stretch polish

### PR DESCRIPTION
**Pull request by PennyQ**
Solved Issues #22 #24 #26 #27 

I am very happy that @astrofrog you could do the issue #25 that related labels have been added to the `options_widget.ui`

The axis show is a a mess now, @maxwelltsai suggested to improve the axis display as a similar way that _Paraview_ does so I will create a new issue for this part.

### CODE REVIEW

**Comment by astrofrog** [comment]
@PennyQ - sorry for the delay, I am reviewing this now

**Comment by astrofrog** [comment]
@PennyQ - this looks good and I **really** like the new stretching, but there is now a test failure we have to resolve before merging:

``` python
=================================== FAILURES ===================================
_________________________________ test_widget __________________________________

    def test_widget():

        # Make sure QApplication is started
        get_qapp()

        # Create fake data
        data = np.arange(1000).reshape((10,10,10))

        # Set up widget
        w = QtVispyWidget()
        w.set_data(data)
        w.add_volume_visual()
        w.canvas.render()

        # Test timer
        w.on_timer(TimerEvent(type='timer_timeout', iteration=3))

        # Test key presses
        # w.on_key_press(KeyEvent(text='1'))
        # w.on_key_press(KeyEvent(text='2'))
        # w.on_key_press(KeyEvent(text='3'))

        # Test mouse_wheel
>       w.on_mouse_wheel(MouseEvent(type='mouse_wheel', delta=(0, 0.5)))

vispy_volume/tests/test_vispy_widget.py:44: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <vispy_volume.vol_vispy_widget.QtVispyWidget object at 0x106cc2828>
event = <vispy_volume.tests.test_vispy_widget.MouseEvent object at 0x10e7dfac8>

    def on_mouse_wheel(self, event):
        if self.view.camera is self.turntableCamera:
>           self.zoom_size = self.ori_distance / self.view.camera.distance
E           TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'

vispy_volume/vol_vispy_widget.py:126: TypeError
----------------------------- Captured stderr call -----------------------------
WARNING: OpenGL version 3.0 or higher recommended, got 2.1 ATI-1.8.19. Some functionality may fail.
WARNING:vispy:OpenGL version 3.0 or higher recommended, got 2.1 ATI-1.8.19. Some functionality may fail.
====================== 1 failed, 1 passed in 3.37 seconds ======================
```

I think `self.view.camera.distance` is `None` in the test for some reason. Any idea why?

**Comment by maxwelltsai** [comment]
@astrofrog Test bug fixed.

**Comment by astrofrog** [comment]
Thanks!

**Pull request merged**
