### PR TITLE
Added unit test and fix failure

### PR DESCRIPTION
**Pull request by astrofrog**
@PennyQ @maxwelltsai - just for information, this adds a first very simple test, although it runs a lot of the code in `vispy_widget.py`. When I ran the test, it failed because `TransFire` and `TransGrays` are not defined inside `vispy_widget.py` so I copied them there.

Is the file `volume_modify.py` still needed?

### CODE REVIEW

**Comment by astrofrog** [comment]
Also you can see that Travis now also runs this test on Python 2.7 and 3.4 to make sure it all runs.

Before committing changes in future, you can check that the test passes by typing

```
py.test vispy_volume
```

(note that you'll need to install pytest with pip or conda first)

**Comment by astrofrog** [comment]
@PennyQ - I'll hold back from merging this until you let me know about whether we can remove `volume_modify.py` or whether it's needed. If it's needed, I can import the `TransGrays` and `TransFire` from there instead of copying them.

**Comment by PennyQ** [comment]
Sorry for the delay, I think the `volume_modify.py` & `config.py` are not needed anymore. So I removed them in my last commit :)
I also moved `TransGrays` and `TransFire` classes into an individual file named `colormaps.py` and color changing functionality is available now.

**Comment by astrofrog** [comment]
@PennyQ - thanks, I've modified this PR to now import the colormaps from the `colormaps.py` file. I'll merge once Travis passes.

**Pull request merged**
