### PR TITLE
Add corner axis

### PR DESCRIPTION
**Pull request by PennyQ**
This would cause fails of most checks, because of the `freeze()` function used by new Vispy. We could try to merge it later when the new Vispy is released.

### CODE REVIEW

**Comment by astrofrog** [comment]
@PennyQ - I fixed the issue with VisPy 0.4 here: https://github.com/PennyQ/glue-3d-viewer/pull/2 - you can merge that PR and it will add the commit to you branch.

**Comment by astrofrog** [comment]
This is looking promising! However, at the moment, the axis doesn't seem to be lined up in the same direction as the white cube axes – do you know why this is?

screen shot 2016-03-18 at 10 53 13 am

**Comment by PennyQ** [comment]
@astrofrog  I guess it's because the `visual` is under the perspective display of the current `camera`, while the `corner axis` is drawn on the `scene` instead of on the `view` of canvas, which means the `axis` is not influenced by the camera setting.

**Comment by PennyQ** [comment]
The direction of the axis is actually the same of camera coordinate (shown below), so I tried to get the transform from camera coor to scene coor as
 `tr = as_matrix_transform(self.get_transform(map_from='visual', map_to='scene'))` and matrix multiply to original transform, but the tr here equals unit matrix. @astrofrog do you have any ideas?

image

**Pull request closed without merging**
