### PR TITLE
On the fly subset highlighting

### PR DESCRIPTION
**Pull request by astrofrog**
Alternative to #42 and #45. This implements the 'full' solution of having 'slots' for the data and subsets in the OpenGL and having the color averaging being done on-the-fly. This also includes an experimental data transparency slider, and fixes issues with the camera jumping.

### CODE REVIEW

**Comment by PennyQ** [comment]
@astrofrog I got an error(as listed below) when I try this 3D volume rendering. Do you know to fix it?

```
2016-02-03 12:49:33.344 python[1339:187766] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/qt/widgets/glue_mdi_area.py", line 62, in dropEvent
    new_layer(layer)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/qt/widgets/glue_mdi_area.py", line 52, in new_layer
    self._application.choose_new_data_viewer(layer)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/qt/glue_application.py", line 675, in choose_new_data_viewer
    return self.do(cmd)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/application_base.py", line 147, in do
    self._cmds.do(command)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/command.py", line 125, in do
    result = cmd.do(self._session)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/command.py", line 215, in do
    v = session.application.new_data_viewer(self.viewer, self.data)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/qt/widgets/mpl_widget.py", line 38, in wrapper
    result = func(*args, **kwargs)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/application_base.py", line 75, in new_data_viewer
    if data and not c.add_data(data):
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/vol_glue_viewer.py", line 65, in add_data
    self._update_data()
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/vol_glue_viewer.py", line 81, in _update_data
    self._vispy_widget.add_volume_visual()
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/vol_vispy_widget.py", line 182, in add_volume_visual
    emulate_texture=self.emulate_texture)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/vispy/scene/visuals.py", line 41, in __init__
    subclass.__init__(self, *args, **kwargs)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/volume_visual.py", line 85, in __init__
    super(MultiVolumeVisual, self).__init__(vcode=vert_shader, fcode=frag_shader)
TypeError: __init__() got an unexpected keyword argument 'vcode' 
```

**Comment by astrofrog** [comment]
@PennyQ - yes, for now you need to use the latest developer version of VisPy. I need to figure out how to get this to work with older versions.

**Comment by PennyQ** [comment]
@astrofrog I still get an error (listed below) with my new but not latest version of Vispy, anyway, I could try it later when you figure out getting it work with current version :)

```
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/volume_visual.py", line 166, in set_volume
    self.shared_program.frag['cmap{0:d}'.format(index)] = Function(cmap.glsl_map)
AttributeError: 'unicode' object has no attribute 'glsl_map'
```

**Comment by astrofrog** [comment]
@PennyQ - can you try again? I think I've made the code compatible with VisPy <= 0.4 and also fixed the Python 2.7 issue.

**Comment by PennyQ** [comment]
@astrofrog Still the same error as `AttributeError: 'unicode' object has no attribute 'glsl_map'`, I also asked @maxwelltsai to try it and he got the same error as mine.

**Comment by astrofrog** [comment]
@PennyQ - can you post the full traceback log?

**Comment by PennyQ** [comment]
@astrofrog Listed as below:

```
Traceback (most recent call last):
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue/qt/widgets/glue_mdi_area.py", line 62, in dropEvent
    new_layer(layer)
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue/qt/widgets/glue_mdi_area.py", line 52, in new_layer
    self._application.choose_new_data_viewer(layer)
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue/qt/glue_application.py", line 675, in choose_new_data_viewer
    return self.do(cmd)
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue/core/application_base.py", line 147, in do
    self._cmds.do(command)
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue/core/command.py", line 125, in do
    result = cmd.do(self._session)
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue/core/command.py", line 215, in do
    v = session.application.new_data_viewer(self.viewer, self.data)
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue/qt/widgets/mpl_widget.py", line 38, in wrapper
    result = func(*args, **kwargs)
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue/core/application_base.py", line 75, in new_data_viewer
    if data and not c.add_data(data):
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/vol_glue_viewer.py", line 65, in add_data
    self._update_data()
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/vol_glue_viewer.py", line 81, in _update_data
    self._vispy_widget.add_volume_visual()
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/vol_vispy_widget.py", line 187, in add_volume_visual
    vol_visual.set_volume('data', vol_data, clim, self.options_widget.cmap)
  File "/Users/penny/anaconda/envs/newvispy/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/volume_visual.py", line 174, in set_volume
    self.shared_program.frag['cmap{0:d}'.format(index)] = Function(cmap.glsl_map)
AttributeError: 'unicode' object has no attribute ‘glsl_map' 
```

**Comment by astrofrog** [comment]
@PennyQ - could you try and make sure you are using the latest version of this branch? The issue should be fixed. The traceback you show indicates the line numbers corresponded to an old version of this branch, so make sure the latest commit is now 7b76e7c

**Comment by astrofrog** [comment]
I'm going to go ahead and merge this because I want to work on the layer artists for this in a separate pull request. @PennyQ, let me know if you still run into issues with the latest version in master once this is merged. I'm not seeing any issues on Python 2.

**Comment by PennyQ** [comment]
@astrofrog Yeah the latest commit works well on the old Vispy version except the subset highlight :(
Here is the error I got when tried subset selection:

I am now working on the layers artist too, should I leave it for you or keep going? 

```
Traceback (most recent call last):
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/qt/data_collection_model.py", line 323, in setData
    self._get_item(index).label = value
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/qt/data_collection_model.py", line 171, in label
    self.subset_group.label = value
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/subset_group.py", line 178, in __setattr__
    self.broadcast(attr)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/subset_group.py", line 173, in broadcast
    s.broadcast(item)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/subset.py", line 242, in broadcast
    self.data.hub.broadcast(msg)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/hub.py", line 180, in broadcast
    handler(message)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/vol_glue_viewer.py", line 73, in _update_subset
    self._update_subsets()
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue_vispy_viewers-0.2.dev0-py2.7.egg/glue_vispy_viewers/volume/vol_glue_viewer.py", line 90, in _update_subsets
    'alpha': s.style.alpha} for s in self._subsets if s.to_mask().ndim == 3])
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glue/core/subset.py", line 210, in to_mask
    raise exc
glue.core.exceptions.IncompatibleAttribute: Pixel x
```

**Comment by astrofrog** [comment]
@PennyQ - can you describe what kind of selection you tried to do?

I'm trying to figure out how to properly implement the layer artists for the volume viewer. I should have something working by tomorrow morning. If you want, you can wait until I have something basic working, so you can see how I did it?

**Comment by PennyQ** [comment]
@astrofrog I just did how we usually showed the subset highlight, like open the 3D volume rendering viewer and 2D image viewer together for the same dataset and then select one part from the image viewer and then got an error as showed above with no subset showed in the 3D volume viewer.

Yeah this sounds great! Do you think the `remove_subset` could also be implemented with this layer artists work? It doesn't work as expected now.

**Comment by astrofrog** [comment]
@PennyQ - yes, once we have the layer artists, the remove will work :)

**Pull request merged**
