### PR TITLE
Added buttons to flip limits

### LINKED ISSUE #70: Add option to flip axis limits

### PR DESCRIPTION
**Pull request by astrofrog**
Currently this looks like this:

screen shot 2016-02-25 at 9 07 02 am

@borkin @PennyQ - I was trying to find a clear but unobtrusive way to do this. Do you think this is intuitive?

Fixes #70

### CODE REVIEW

**Comment by PennyQ** [comment]
@astrofrog Yeah it's very clear to me except this icon image between max & min text box. What's it for?

**Comment by borkin** [comment]
@astrofroghttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_astrofrog&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=PPKbA3gSrhZ0r0pFtkZLpCPOmU2uXS4VZkPr-isl_EQ&m=MESVxw8l7Om8Fp0GoXlBmrMJL4lAUgVAUogtfnSrX-Y&s=j_3JQg7hpyrBTImd5WfVYoEk0RmqbuOJYfsLR20yDUI&e= All looks good to me but I do agree with Penny that “<>” is not intuitive for “flip limits”…

Perhaps a double-headed arrow icon instead of <>?  Or put a word between the brackets like <-swap-> or <-flip->?

On Feb 25, 2016, at 3:36 PM, Penny Qian <notifications@github.com<mailto:notifications@github.com>> wrote:

@astrofroghttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_astrofrog&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=PPKbA3gSrhZ0r0pFtkZLpCPOmU2uXS4VZkPr-isl_EQ&m=MESVxw8l7Om8Fp0GoXlBmrMJL4lAUgVAUogtfnSrX-Y&s=j_3JQg7hpyrBTImd5WfVYoEk0RmqbuOJYfsLR20yDUI&e= Yeah it's very clear to me except this icon [image] https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_13411839_13333477_48802722-2Ddbd5-2D11e5-2D874b-2D6d97780f60eb.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=PPKbA3gSrhZ0r0pFtkZLpCPOmU2uXS4VZkPr-isl_EQ&m=MESVxw8l7Om8Fp0GoXlBmrMJL4lAUgVAUogtfnSrX-Y&s=iYtk-RUAs0-kQBp4_MhNSmvTmoY2N4r9Qn-uBrUpaHs&e=  between max & min text box. What's it for?

**Comment by astrofrog** [comment]
@borkin @PennyQ - what about this?

screen shot 2016-02-25 at 9 31 38 pm

**Comment by astrofrog** [comment]
Ideally I'd prefer if it took up less space, but we'd need to make sure it's intuitive. Maybe there is a symbol/icon we can use?

**Comment by borkin** [comment]
This looks better, but I agree that a space-saving icon would be better…

Is there any generic text/symbol character we could use such as one of the following?

⇄
↔
⇔

On Feb 25, 2016, at 4:32 PM, Thomas Robitaille <notifications@github.com<mailto:notifications@github.com>> wrote:

Ideally I'd prefer if it took up less space, but we'd need to make sure it's intuitive. Maybe there is a symbol/icon we can use?

**Comment by astrofrog** [comment]
@borkin - perfect, thanks for the suggestions! Does this look better?

screen shot 2016-02-25 at 9 44 02 pm

**Comment by borkin** [comment]
Love it, looks good to me! :)  What do you think @PennyQhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PennyQ&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=PPKbA3gSrhZ0r0pFtkZLpCPOmU2uXS4VZkPr-isl_EQ&m=PeKU32xs9AoqJwEnasLkWSNBDR7IQSMNUaMoyrSoWsY&s=F-ObnBLWryxBZVyg9N3Qa-glRMFB2uW2rIOIwh0vQmw&e= ?

On Feb 25, 2016, at 4:44 PM, Thomas Robitaille <notifications@github.com<mailto:notifications@github.com>> wrote:

@borkinhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_borkin&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=PPKbA3gSrhZ0r0pFtkZLpCPOmU2uXS4VZkPr-isl_EQ&m=zKjF3nxhqM6XettaQR1_xyo36N2lHg3k0gBks73ULJ4&s=vpRGDorMIXb3NhFb0rqEZsc1sDzPdmbOLxJw3wJhZks&e= - perfect, thanks for the suggestions! Does this look better?

[screen shot 2016-02-25 at 9 44 02 pm]https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_314716_13335428_fa9ff670-2Ddc08-2D11e5-2D9c40-2D77f6e72337b5.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=PPKbA3gSrhZ0r0pFtkZLpCPOmU2uXS4VZkPr-isl_EQ&m=zKjF3nxhqM6XettaQR1_xyo36N2lHg3k0gBks73ULJ4&s=jzofm7zIMAtfhY745RKpp7pPpoetG4MqxHnqVgO0OKA&e=

**Comment by PennyQ** [comment]
It looks good for me. I don't know why I always think it to be a button that we could click...

**Pull request merged**
