### PR TITLE
add icon for rotate view

### PR DESCRIPTION
**Pull request by PennyQ**
Add an icon for rotate view as shown below, close the PR #119 

image

### CODE REVIEW

**Comment by astrofrog** [comment]
@PennyQ - looks great! Can you reduce the size of the PNG file to 125x125 pixels? (it doesn't need to be as big as it is right now)

**Comment by astrofrog** [comment]
@PennyQ - can you also make the background transparent instead of grey? (maybe do this _before_ reducing the size to 125x125). Otherwise, this works great!

**Comment by PennyQ** [comment]
@astrofrog Change the figure, merge this?

**Comment by astrofrog** [comment]
@PennyQ - before I merge, remove the current changes from the CHANGES.md file (see the diff in this PR to see the issues), and add a new entry to CHANGES.md to mention the addition of the icon. Once you've done this, rebase again and this time squash all the commits into a single one (I can help you on Gitter if needed)

**Comment by PennyQ** [comment]
@astrofrog Thanks for the instruction, it works and here is the code:)

**Comment by astrofrog** [comment]
@PennyQ - thanks, almost there! There are a couple of entries in the CHANGES.md file that shouldn't be there (you can see those lines appear twice now in the 0.3 section). So remove the ones that shouldn't be changed here, commit, then rebase again to squash. This time, the rebasing should be easy though and there should be no conflicts (don't do any merging)

**Comment by PennyQ** [comment]
@astrofrog I think this time it's 'really' done :)

**Comment by astrofrog** [comment]
Perfect, thanks!

**Pull request merged**
