### PR TITLE
Fix Qt imports

### PR DESCRIPTION
**Pull request by astrofrog**
@PennyQ - this will fix the issue you were seeing. Basically we are switching to using QtPy instead of glue.external.qt - QtPy is basically a package that behaves like PyQt5 but also works with PyQt4 and PySide (it's just a wrapper).

### CODE REVIEW

**Comment by astrofrog** [comment]
@PennyQ - can you confirm that everything works fine now?

**Comment by PennyQ** [comment]
@astrofrog The 3D viewers still don't get loaded with the following errors: 

> INFO:glue:Loading plugin vispy_volume failed (Exception: No module named QtGui)
> INFO:glue:Loading plugin vispy_isosurface failed (Exception: cannot import name QtGui)
> INFO:glue:Loading plugin vispy_scatter failed (Exception: cannot import name QtGui)
> INFO:glue:Loading plugin dendrogram_selection failed (Exception: cannot import name QtGui)
> INFO:glue:Loading plugin floodfill_selection failed (Exception: cannot import name QtGui)
> INFO:glue:Loading plugin contour_selection failed (Exception: cannot import name QtGui)
> INFO:glue:Loading plugin vizier_importer failed (Exception: cannot import name QtGui)

Also an error happened when I tried to set bgcolor in user preference as below:

> INFO:glue:An error occured when accessing attribute ui.combo_theme of <glue.app.qt.preferences.PreferencesDialog object at 0x1212e7180>. Returning None.
> Traceback (most recent call last):
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/misc.py", line 57, in result
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/qt/colors.py", line 161, in query_color
>     color = QtGui.QColorDialog.getColor(self._qcolor, parent=self)
> AttributeError: 'module' object has no attribute 'QColorDialog'

**Comment by astrofrog** [comment]
@PennyQ - ok np, will investigate

**Comment by astrofrog** [comment]
@PennyQ - can you try again? Make sure you install the latest developer version of this plugin and the glue-exp one.

**Comment by PennyQ** [comment]
@astrofrog yes I got all 3d viewers back, but the color setting in user preferences still has the same error as above.

**Pull request merged**
